services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /docker/ssl/certs:/etc/nginx/certs
      - /docker/ssl/vhost.d:/etc/nginx/vhost.d
      - /docker/ssl/html:/usr/share/nginx/html
      - /etc/nginx/conf.d
    environment:
      - DEFAULT_HOST=eduwave.eduardlupu.com
    networks:
      - diss-network
    restart: always

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/ssl/certs:/etc/nginx/certs
      - /docker/ssl/vhost.d:/etc/nginx/vhost.d
      - /docker/ssl/html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=lupu.edward2@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - diss-network
    restart: always

  postgres:
    image: 'postgres:15-alpine'
    env_file:
      - environment/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - diss-network
    restart: always

  pgadmin:
    image: 'dpage/pgadmin4:6.15'
    env_file:
      - environment/pgadmin.env
    ports:
      - "8081:80"
    networks:
      - diss-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: eduwave.eduardlupu.com
      LETSENCRYPT_HOST: eduwave.eduardlupu.com
      LETSENCRYPT_EMAIL: lupu.edward2@gmail.com
    networks:
      - diss-network
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - frontend
      - pgadmin
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dissdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpassword
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DDL_AUTO: update
      VIRTUAL_HOST: api.eduwave.eduardlupu.com
      LETSENCRYPT_HOST: api.eduwave.eduardlupu.com
      LETSENCRYPT_EMAIL: lupu.edward2@gmail.com
    networks:
      - diss-network
    restart: always

volumes:
  postgres_data:
  pgadmin_data:

networks:
  diss-network:
    driver: bridge
    name: diss-network
