name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy project files to Azure VM
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          source: |
            client/
            server/
            docker-compose.yml
            .env
            nginx.conf
          target: "/home/${{ secrets.AZURE_VM_USER }}/diss-project"
          rm: false

      - name: Rebuild Docker and Restart
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            cd /home/${{ secrets.AZURE_VM_USER }}/diss-project
            sudo docker compose up --build -d